### ISSUE TITLE
Strange scroll behavior after removing .appleScrollBehavior

### ISSUE THREAD

**Issue by LinusGeffarth** [lucaszischka/BottomSheet#54] opened 2022-03-03 15:31 UTC
Using `.appleScrollBehavior` disabled my buttons in the sheet, no matter at which position it was. So, I removed this option. I am now able to tap buttons in the sheet, but look at how strangely this scrolls:

https://user-images.githubusercontent.com/9455439/156595983-44a3783f-7d16-4da1-90f6-d9e4c57062a8.mp4

It's almost as if I had extra springy animations set – which I don't.  
In the `mainContent`, I simply have a `VStack` that holds a `ForEach` of a bunch of buttons.

Any idea what's wrong and what I can do about it?

**Comment by lucaszischka** [comment] 2022-03-07 08:19
Did you install this library using cocapods? If so, please use SPM and try again. The current pod version is not up to date. I will update it soon.

**Comment by LinusGeffarth** [comment] 2022-03-07 09:22
No was installed using SPM and on the latest version pulled from `master`.
The issue went away after letting Xcode sit for a night...maybe still worth investigating.

**Comment by LinusGeffarth** [comment] 2022-03-08 09:54
can't really share it as it's proprietary, but the thing is I also didn't change that.
here's the rough view structure though:

```
Map
  .bottomSheet maintContent: {
    ForEach
      Button
        VStack
          ...
}
```

**Comment by lucaszischka** [comment] 2022-03-08 10:11
Thus code looks fine. Did you use any `.transition` or `.animation` modifiers in your view?

**Comment by LinusGeffarth** [comment] 2022-03-08 10:19
No, none

**Comment by lucaszischka** [comment] 2022-03-08 10:30
Then I don’t know what caused this issue. But because it resolved itself and is no longer reproduceable I will close this issue now. Thanks for your help!

**Closed by lucaszischka** 2022-03-08 10:30 UTC

**Comment by LinusGeffarth** [comment] 2022-03-08 10:35
Yeah, I'm sorry this bug report is so fuzzy. If I see the issue again, I will make sure to provide more context.
Thanks for looking into this though!
